// Presidential elections 1989-2022, national totals computed from TSE open data
// (dadosabertos.tse.jus.br: detalhe_votacao_* and votacao_candidato_*, cargo Presidente).
// Generated by aggregating every municipality/zone row; percentages are computed in the page.
window.HIST_ELEICOES = [
 {
  "ano": 1989,
  "fonte": [
   "https://cdn.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_uf/detalhe_votacao_uf_1989.zip",
   "https://cdn.tse.jus.br/estatistica/sead/odsele/votacao_candidato_uf/votacao_candidato_uf_1989.zip"
  ],
  "turnos": {
   "1": {
    "aptos": 82074718,
    "comparecimento": 72290216,
    "abstencoes": 9784502,
    "brancos": 1176367,
    "nulos": 3487963,
    "validos": 67625886,
    "candidatos": [
     {
      "n": "20",
      "nome": "Collor",
      "partido": "PRN",
      "votos": 20611030
     },
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 11622321
     },
     {
      "n": "12",
      "nome": "Brizola",
      "partido": "PDT",
      "votos": 11167665
     }
    ]
   },
   "2": {
    "aptos": 82074718,
    "comparecimento": 70260701,
    "abstencoes": 11814017,
    "brancos": 986460,
    "nulos": 3108232,
    "validos": 66166009,
    "candidatos": [
     {
      "n": "20",
      "nome": "Collor",
      "partido": "PRN",
      "votos": 35090206
     },
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 31075803
     }
    ]
   }
  }
 },
 {
  "ano": 1994,
  "fonte": [
   "https://cdn.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_1994.zip",
   "https://cdn.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_1994.zip"
  ],
  "turnos": {
   "1": {
    "aptos": 94710636,
    "comparecimento": 77920633,
    "abstencoes": 16790003,
    "brancos": 7191856,
    "nulos": 7443144,
    "validos": 63285633,
    "candidatos": [
     {
      "n": "45",
      "nome": "FHC",
      "partido": "PSDB",
      "votos": 34350217
     },
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 17112255
     },
     {
      "n": "56",
      "nome": "Enéas",
      "partido": "PRONA",
      "votos": 4670894
     }
    ]
   }
  }
 },
 {
  "ano": 1998,
  "fonte": [
   "https://cdn.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_1998.zip",
   "https://cdn.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_1998.zip"
  ],
  "turnos": {
   "1": {
    "aptos": 106100575,
    "comparecimento": 83297773,
    "abstencoes": 22802802,
    "brancos": 6688379,
    "nulos": 8887091,
    "validos": 67722303,
    "candidatos": [
     {
      "n": "45",
      "nome": "FHC",
      "partido": "PSDB",
      "votos": 35936382
     },
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 21475211
     },
     {
      "n": "23",
      "nome": "Ciro Gomes",
      "partido": "PPS",
      "votos": 7426187
     }
    ]
   }
  }
 },
 {
  "ano": 2002,
  "fonte": [
   "https://cdn.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_2002.zip",
   "https://cdn.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_2002.zip"
  ],
  "turnos": {
   "1": {
    "aptos": 115253816,
    "comparecimento": 94805583,
    "abstencoes": 20448233,
    "brancos": 2873753,
    "nulos": 6976685,
    "validos": 84952512,
    "candidatos": [
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 39455233
     },
     {
      "n": "45",
      "nome": "José Serra",
      "partido": "PSDB",
      "votos": 19705445
     },
     {
      "n": "40",
      "nome": "Garotinho",
      "partido": "PSB",
      "votos": 15180097
     }
    ]
   },
   "2": {
    "aptos": 115253816,
    "comparecimento": 91664259,
    "abstencoes": 23589188,
    "brancos": 1727760,
    "nulos": 3772138,
    "validos": 86164103,
    "candidatos": [
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 52793364
     },
     {
      "n": "45",
      "nome": "José Serra",
      "partido": "PSDB",
      "votos": 33370739
     }
    ]
   }
  }
 },
 {
  "ano": 2006,
  "fonte": [
   "https://cdn.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_2006.zip",
   "https://cdn.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_2006.zip"
  ],
  "turnos": {
   "1": {
    "aptos": 125913235,
    "comparecimento": 104820459,
    "abstencoes": 21092675,
    "brancos": 2866205,
    "nulos": 5938645,
    "validos": 95996733,
    "candidatos": [
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 46662365
     },
     {
      "n": "45",
      "nome": "Geraldo Alckmin",
      "partido": "PSDB",
      "votos": 39968369
     },
     {
      "n": "50",
      "nome": "Heloísa Helena",
      "partido": "PSOL",
      "votos": 6575393
     }
    ]
   },
   "2": {
    "aptos": 125913235,
    "comparecimento": 101998221,
    "abstencoes": 23914714,
    "brancos": 1351448,
    "nulos": 4789677,
    "validos": 95838220,
    "candidatos": [
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 58295042
     },
     {
      "n": "45",
      "nome": "Geraldo Alckmin",
      "partido": "PSDB",
      "votos": 37543178
     }
    ]
   }
  }
 },
 {
  "ano": 2010,
  "fonte": [
   "https://cdn.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_2010.zip",
   "https://cdn.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_2010.zip"
  ],
  "turnos": {
   "1": {
    "aptos": 135804433,
    "comparecimento": 111193747,
    "abstencoes": 24610296,
    "brancos": 3479340,
    "nulos": 6124254,
    "validos": 101590153,
    "candidatos": [
     {
      "n": "13",
      "nome": "Dilma",
      "partido": "PT",
      "votos": 47651434
     },
     {
      "n": "45",
      "nome": "José Serra",
      "partido": "PSDB",
      "votos": 33132283
     },
     {
      "n": "43",
      "nome": "Marina Silva",
      "partido": "PV",
      "votos": 19636359
     }
    ]
   },
   "2": {
    "aptos": 135804433,
    "comparecimento": 106606214,
    "abstencoes": 29197152,
    "brancos": 2452597,
    "nulos": 4689428,
    "validos": 99463917,
    "candidatos": [
     {
      "n": "13",
      "nome": "Dilma",
      "partido": "PT",
      "votos": 55752529
     },
     {
      "n": "45",
      "nome": "José Serra",
      "partido": "PSDB",
      "votos": 43711388
     }
    ]
   }
  }
 },
 {
  "ano": 2014,
  "fonte": [
   "https://cdn.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_2014.zip",
   "https://cdn.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_2014.zip"
  ],
  "turnos": {
   "1": {
    "aptos": 142822046,
    "comparecimento": 115122883,
    "abstencoes": 27698475,
    "brancos": 4420489,
    "nulos": 6678592,
    "validos": 104023802,
    "candidatos": [
     {
      "n": "13",
      "nome": "Dilma",
      "partido": "PT",
      "votos": 43267668
     },
     {
      "n": "45",
      "nome": "Aécio Neves",
      "partido": "PSDB",
      "votos": 34897211
     },
     {
      "n": "40",
      "nome": "Marina Silva",
      "partido": "PSB",
      "votos": 22176619
     }
    ]
   },
   "2": {
    "aptos": 142822046,
    "comparecimento": 112683879,
    "abstencoes": 30137479,
    "brancos": 1921819,
    "nulos": 5219787,
    "validos": 105542273,
    "candidatos": [
     {
      "n": "13",
      "nome": "Dilma",
      "partido": "PT",
      "votos": 54501118
     },
     {
      "n": "45",
      "nome": "Aécio Neves",
      "partido": "PSDB",
      "votos": 51041155
     }
    ]
   }
  }
 },
 {
  "ano": 2018,
  "fonte": [
   "https://cdn.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_2018.zip",
   "https://cdn.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_2018.zip"
  ],
  "turnos": {
   "1": {
    "aptos": 147306295,
    "comparecimento": 117364654,
    "abstencoes": 29941171,
    "brancos": 3106937,
    "nulos": 7206222,
    "validos": 107050749,
    "candidatos": [
     {
      "n": "17",
      "nome": "Jair Bolsonaro",
      "partido": "PSL",
      "votos": 49277010
     },
     {
      "n": "13",
      "nome": "Fernando Haddad",
      "partido": "PT",
      "votos": 31342051
     },
     {
      "n": "12",
      "nome": "Ciro Gomes",
      "partido": "PDT",
      "votos": 13344371
     }
    ]
   },
   "2": {
    "aptos": 147306294,
    "comparecimento": 115933451,
    "abstencoes": 31372373,
    "brancos": 2486593,
    "nulos": 8608105,
    "validos": 104838753,
    "candidatos": [
     {
      "n": "17",
      "nome": "Jair Bolsonaro",
      "partido": "PSL",
      "votos": 57797847
     },
     {
      "n": "13",
      "nome": "Fernando Haddad",
      "partido": "PT",
      "votos": 47040906
     }
    ]
   }
  }
 },
 {
  "ano": 2022,
  "fonte": [
   "https://cdn.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_2022.zip",
   "https://cdn.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_2022.zip"
  ],
  "turnos": {
   "1": {
    "aptos": 156454011,
    "comparecimento": 123682372,
    "abstencoes": 32770982,
    "brancos": 1964779,
    "nulos": 3487874,
    "validos": 118229719,
    "candidatos": [
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 57259504
     },
     {
      "n": "22",
      "nome": "Jair Bolsonaro",
      "partido": "PL",
      "votos": 51072345
     },
     {
      "n": "15",
      "nome": "Simone Tebet",
      "partido": "MDB",
      "votos": 4915423
     }
    ]
   },
   "2": {
    "aptos": 156454011,
    "comparecimento": 124252796,
    "abstencoes": 32200558,
    "brancos": 1769678,
    "nulos": 3930765,
    "validos": 118552353,
    "candidatos": [
     {
      "n": "13",
      "nome": "Lula",
      "partido": "PT",
      "votos": 60345999
     },
     {
      "n": "22",
      "nome": "Jair Bolsonaro",
      "partido": "PL",
      "votos": 58206354
     }
    ]
   }
  }
 }
];
